/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IETSAuctionHouse {
  export type AuctionStruct = {
    auctionId: BigNumberish;
    amount: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    reservePrice: BigNumberish;
    bidder: AddressLike;
    auctioneer: AddressLike;
    settled: boolean;
  };

  export type AuctionStructOutput = [
    auctionId: bigint,
    amount: bigint,
    startTime: bigint,
    endTime: bigint,
    reservePrice: bigint,
    bidder: string,
    auctioneer: string,
    settled: boolean
  ] & {
    auctionId: bigint;
    amount: bigint;
    startTime: bigint;
    endTime: bigint;
    reservePrice: bigint;
    bidder: string;
    auctioneer: string;
    settled: boolean;
  };
}

export interface IETSAuctionHouseInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "auctionEnded"
      | "auctionExists"
      | "auctionSettled"
      | "createBid"
      | "createNextAuction"
      | "drawDown"
      | "fulfillRequestCreateAuction"
      | "getActiveCount"
      | "getAuction"
      | "getBalance"
      | "getTotalCount"
      | "pause"
      | "setProceedPercentages"
      | "setReservePrice"
      | "setTimeBuffer"
      | "settleAuction"
      | "settleCurrentAndCreateNewAuction"
      | "totalDue"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuctionBid"
      | "AuctionCreated"
      | "AuctionDurationSet"
      | "AuctionExtended"
      | "AuctionMinBidIncrementPercentageSet"
      | "AuctionProceedPercentagesSet"
      | "AuctionProceedsWithdrawn"
      | "AuctionReservePriceSet"
      | "AuctionSettled"
      | "AuctionTimeBufferSet"
      | "AuctionsMaxSet"
      | "RequestCreateAuction"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "auctionEnded",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "auctionExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "auctionSettled",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createBid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createNextAuction",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "drawDown",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fulfillRequestCreateAuction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAuction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setProceedPercentages",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setReservePrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTimeBuffer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settleAuction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settleCurrentAndCreateNewAuction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalDue",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "auctionEnded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "auctionExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "auctionSettled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createNextAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "drawDown", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fulfillRequestCreateAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAuction", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setProceedPercentages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReservePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTimeBuffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleCurrentAndCreateNewAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalDue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace AuctionBidEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    sender: AddressLike,
    value: BigNumberish,
    extended: boolean
  ];
  export type OutputTuple = [
    tokenId: bigint,
    sender: string,
    value: bigint,
    extended: boolean
  ];
  export interface OutputObject {
    tokenId: bigint;
    sender: string;
    value: bigint;
    extended: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionCreatedEvent {
  export type InputTuple = [tokenId: BigNumberish, auctionNumber: BigNumberish];
  export type OutputTuple = [tokenId: bigint, auctionNumber: bigint];
  export interface OutputObject {
    tokenId: bigint;
    auctionNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionDurationSetEvent {
  export type InputTuple = [duration: BigNumberish];
  export type OutputTuple = [duration: bigint];
  export interface OutputObject {
    duration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionExtendedEvent {
  export type InputTuple = [tokenId: BigNumberish, endTime: BigNumberish];
  export type OutputTuple = [tokenId: bigint, endTime: bigint];
  export interface OutputObject {
    tokenId: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionMinBidIncrementPercentageSetEvent {
  export type InputTuple = [minBidIncrementPercentagePrice: BigNumberish];
  export type OutputTuple = [minBidIncrementPercentagePrice: bigint];
  export interface OutputObject {
    minBidIncrementPercentagePrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionProceedPercentagesSetEvent {
  export type InputTuple = [
    platformPercentage: BigNumberish,
    relayerPercentage: BigNumberish,
    creatorPercentage: BigNumberish
  ];
  export type OutputTuple = [
    platformPercentage: bigint,
    relayerPercentage: bigint,
    creatorPercentage: bigint
  ];
  export interface OutputObject {
    platformPercentage: bigint;
    relayerPercentage: bigint;
    creatorPercentage: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionProceedsWithdrawnEvent {
  export type InputTuple = [who: AddressLike, amount: BigNumberish];
  export type OutputTuple = [who: string, amount: bigint];
  export interface OutputObject {
    who: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionReservePriceSetEvent {
  export type InputTuple = [reservePrice: BigNumberish];
  export type OutputTuple = [reservePrice: bigint];
  export interface OutputObject {
    reservePrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionSettledEvent {
  export type InputTuple = [tokenId: BigNumberish];
  export type OutputTuple = [tokenId: bigint];
  export interface OutputObject {
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionTimeBufferSetEvent {
  export type InputTuple = [timeBuffer: BigNumberish];
  export type OutputTuple = [timeBuffer: bigint];
  export interface OutputObject {
    timeBuffer: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionsMaxSetEvent {
  export type InputTuple = [maxAuctions: BigNumberish];
  export type OutputTuple = [maxAuctions: bigint];
  export interface OutputObject {
    maxAuctions: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestCreateAuctionEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IETSAuctionHouse extends BaseContract {
  connect(runner?: ContractRunner | null): IETSAuctionHouse;
  waitForDeployment(): Promise<this>;

  interface: IETSAuctionHouseInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  auctionEnded: TypedContractMethod<
    [_tokenId: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  auctionExists: TypedContractMethod<
    [_tokenId: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  auctionSettled: TypedContractMethod<
    [_tokenId: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  createBid: TypedContractMethod<[auctionId: BigNumberish], [void], "payable">;

  createNextAuction: TypedContractMethod<[], [void], "nonpayable">;

  drawDown: TypedContractMethod<[_account: AddressLike], [void], "nonpayable">;

  fulfillRequestCreateAuction: TypedContractMethod<
    [_tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getActiveCount: TypedContractMethod<[], [bigint], "nonpayable">;

  getAuction: TypedContractMethod<
    [_tokenId: BigNumberish],
    [IETSAuctionHouse.AuctionStructOutput],
    "nonpayable"
  >;

  getBalance: TypedContractMethod<[], [bigint], "nonpayable">;

  getTotalCount: TypedContractMethod<[], [bigint], "nonpayable">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  setProceedPercentages: TypedContractMethod<
    [_platformPercentage: BigNumberish, _relayerPercentage: BigNumberish],
    [void],
    "nonpayable"
  >;

  setReservePrice: TypedContractMethod<
    [_reservePrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTimeBuffer: TypedContractMethod<
    [timeBuffer: BigNumberish],
    [void],
    "nonpayable"
  >;

  settleAuction: TypedContractMethod<
    [_tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  settleCurrentAndCreateNewAuction: TypedContractMethod<
    [_tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalDue: TypedContractMethod<
    [_account: AddressLike],
    [bigint],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "auctionEnded"
  ): TypedContractMethod<[_tokenId: BigNumberish], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "auctionExists"
  ): TypedContractMethod<[_tokenId: BigNumberish], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "auctionSettled"
  ): TypedContractMethod<[_tokenId: BigNumberish], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "createBid"
  ): TypedContractMethod<[auctionId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "createNextAuction"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "drawDown"
  ): TypedContractMethod<[_account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fulfillRequestCreateAuction"
  ): TypedContractMethod<[_tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveCount"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "getAuction"
  ): TypedContractMethod<
    [_tokenId: BigNumberish],
    [IETSAuctionHouse.AuctionStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "getTotalCount"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setProceedPercentages"
  ): TypedContractMethod<
    [_platformPercentage: BigNumberish, _relayerPercentage: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setReservePrice"
  ): TypedContractMethod<[_reservePrice: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTimeBuffer"
  ): TypedContractMethod<[timeBuffer: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleAuction"
  ): TypedContractMethod<[_tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleCurrentAndCreateNewAuction"
  ): TypedContractMethod<[_tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalDue"
  ): TypedContractMethod<[_account: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AuctionBid"
  ): TypedContractEvent<
    AuctionBidEvent.InputTuple,
    AuctionBidEvent.OutputTuple,
    AuctionBidEvent.OutputObject
  >;
  getEvent(
    key: "AuctionCreated"
  ): TypedContractEvent<
    AuctionCreatedEvent.InputTuple,
    AuctionCreatedEvent.OutputTuple,
    AuctionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AuctionDurationSet"
  ): TypedContractEvent<
    AuctionDurationSetEvent.InputTuple,
    AuctionDurationSetEvent.OutputTuple,
    AuctionDurationSetEvent.OutputObject
  >;
  getEvent(
    key: "AuctionExtended"
  ): TypedContractEvent<
    AuctionExtendedEvent.InputTuple,
    AuctionExtendedEvent.OutputTuple,
    AuctionExtendedEvent.OutputObject
  >;
  getEvent(
    key: "AuctionMinBidIncrementPercentageSet"
  ): TypedContractEvent<
    AuctionMinBidIncrementPercentageSetEvent.InputTuple,
    AuctionMinBidIncrementPercentageSetEvent.OutputTuple,
    AuctionMinBidIncrementPercentageSetEvent.OutputObject
  >;
  getEvent(
    key: "AuctionProceedPercentagesSet"
  ): TypedContractEvent<
    AuctionProceedPercentagesSetEvent.InputTuple,
    AuctionProceedPercentagesSetEvent.OutputTuple,
    AuctionProceedPercentagesSetEvent.OutputObject
  >;
  getEvent(
    key: "AuctionProceedsWithdrawn"
  ): TypedContractEvent<
    AuctionProceedsWithdrawnEvent.InputTuple,
    AuctionProceedsWithdrawnEvent.OutputTuple,
    AuctionProceedsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "AuctionReservePriceSet"
  ): TypedContractEvent<
    AuctionReservePriceSetEvent.InputTuple,
    AuctionReservePriceSetEvent.OutputTuple,
    AuctionReservePriceSetEvent.OutputObject
  >;
  getEvent(
    key: "AuctionSettled"
  ): TypedContractEvent<
    AuctionSettledEvent.InputTuple,
    AuctionSettledEvent.OutputTuple,
    AuctionSettledEvent.OutputObject
  >;
  getEvent(
    key: "AuctionTimeBufferSet"
  ): TypedContractEvent<
    AuctionTimeBufferSetEvent.InputTuple,
    AuctionTimeBufferSetEvent.OutputTuple,
    AuctionTimeBufferSetEvent.OutputObject
  >;
  getEvent(
    key: "AuctionsMaxSet"
  ): TypedContractEvent<
    AuctionsMaxSetEvent.InputTuple,
    AuctionsMaxSetEvent.OutputTuple,
    AuctionsMaxSetEvent.OutputObject
  >;
  getEvent(
    key: "RequestCreateAuction"
  ): TypedContractEvent<
    RequestCreateAuctionEvent.InputTuple,
    RequestCreateAuctionEvent.OutputTuple,
    RequestCreateAuctionEvent.OutputObject
  >;

  filters: {
    "AuctionBid(uint256,address,uint256,bool)": TypedContractEvent<
      AuctionBidEvent.InputTuple,
      AuctionBidEvent.OutputTuple,
      AuctionBidEvent.OutputObject
    >;
    AuctionBid: TypedContractEvent<
      AuctionBidEvent.InputTuple,
      AuctionBidEvent.OutputTuple,
      AuctionBidEvent.OutputObject
    >;

    "AuctionCreated(uint256,uint256)": TypedContractEvent<
      AuctionCreatedEvent.InputTuple,
      AuctionCreatedEvent.OutputTuple,
      AuctionCreatedEvent.OutputObject
    >;
    AuctionCreated: TypedContractEvent<
      AuctionCreatedEvent.InputTuple,
      AuctionCreatedEvent.OutputTuple,
      AuctionCreatedEvent.OutputObject
    >;

    "AuctionDurationSet(uint256)": TypedContractEvent<
      AuctionDurationSetEvent.InputTuple,
      AuctionDurationSetEvent.OutputTuple,
      AuctionDurationSetEvent.OutputObject
    >;
    AuctionDurationSet: TypedContractEvent<
      AuctionDurationSetEvent.InputTuple,
      AuctionDurationSetEvent.OutputTuple,
      AuctionDurationSetEvent.OutputObject
    >;

    "AuctionExtended(uint256,uint256)": TypedContractEvent<
      AuctionExtendedEvent.InputTuple,
      AuctionExtendedEvent.OutputTuple,
      AuctionExtendedEvent.OutputObject
    >;
    AuctionExtended: TypedContractEvent<
      AuctionExtendedEvent.InputTuple,
      AuctionExtendedEvent.OutputTuple,
      AuctionExtendedEvent.OutputObject
    >;

    "AuctionMinBidIncrementPercentageSet(uint8)": TypedContractEvent<
      AuctionMinBidIncrementPercentageSetEvent.InputTuple,
      AuctionMinBidIncrementPercentageSetEvent.OutputTuple,
      AuctionMinBidIncrementPercentageSetEvent.OutputObject
    >;
    AuctionMinBidIncrementPercentageSet: TypedContractEvent<
      AuctionMinBidIncrementPercentageSetEvent.InputTuple,
      AuctionMinBidIncrementPercentageSetEvent.OutputTuple,
      AuctionMinBidIncrementPercentageSetEvent.OutputObject
    >;

    "AuctionProceedPercentagesSet(uint256,uint256,uint256)": TypedContractEvent<
      AuctionProceedPercentagesSetEvent.InputTuple,
      AuctionProceedPercentagesSetEvent.OutputTuple,
      AuctionProceedPercentagesSetEvent.OutputObject
    >;
    AuctionProceedPercentagesSet: TypedContractEvent<
      AuctionProceedPercentagesSetEvent.InputTuple,
      AuctionProceedPercentagesSetEvent.OutputTuple,
      AuctionProceedPercentagesSetEvent.OutputObject
    >;

    "AuctionProceedsWithdrawn(address,uint256)": TypedContractEvent<
      AuctionProceedsWithdrawnEvent.InputTuple,
      AuctionProceedsWithdrawnEvent.OutputTuple,
      AuctionProceedsWithdrawnEvent.OutputObject
    >;
    AuctionProceedsWithdrawn: TypedContractEvent<
      AuctionProceedsWithdrawnEvent.InputTuple,
      AuctionProceedsWithdrawnEvent.OutputTuple,
      AuctionProceedsWithdrawnEvent.OutputObject
    >;

    "AuctionReservePriceSet(uint256)": TypedContractEvent<
      AuctionReservePriceSetEvent.InputTuple,
      AuctionReservePriceSetEvent.OutputTuple,
      AuctionReservePriceSetEvent.OutputObject
    >;
    AuctionReservePriceSet: TypedContractEvent<
      AuctionReservePriceSetEvent.InputTuple,
      AuctionReservePriceSetEvent.OutputTuple,
      AuctionReservePriceSetEvent.OutputObject
    >;

    "AuctionSettled(uint256)": TypedContractEvent<
      AuctionSettledEvent.InputTuple,
      AuctionSettledEvent.OutputTuple,
      AuctionSettledEvent.OutputObject
    >;
    AuctionSettled: TypedContractEvent<
      AuctionSettledEvent.InputTuple,
      AuctionSettledEvent.OutputTuple,
      AuctionSettledEvent.OutputObject
    >;

    "AuctionTimeBufferSet(uint256)": TypedContractEvent<
      AuctionTimeBufferSetEvent.InputTuple,
      AuctionTimeBufferSetEvent.OutputTuple,
      AuctionTimeBufferSetEvent.OutputObject
    >;
    AuctionTimeBufferSet: TypedContractEvent<
      AuctionTimeBufferSetEvent.InputTuple,
      AuctionTimeBufferSetEvent.OutputTuple,
      AuctionTimeBufferSetEvent.OutputObject
    >;

    "AuctionsMaxSet(uint256)": TypedContractEvent<
      AuctionsMaxSetEvent.InputTuple,
      AuctionsMaxSetEvent.OutputTuple,
      AuctionsMaxSetEvent.OutputObject
    >;
    AuctionsMaxSet: TypedContractEvent<
      AuctionsMaxSetEvent.InputTuple,
      AuctionsMaxSetEvent.OutputTuple,
      AuctionsMaxSetEvent.OutputObject
    >;

    "RequestCreateAuction()": TypedContractEvent<
      RequestCreateAuctionEvent.InputTuple,
      RequestCreateAuctionEvent.OutputTuple,
      RequestCreateAuctionEvent.OutputObject
    >;
    RequestCreateAuction: TypedContractEvent<
      RequestCreateAuctionEvent.InputTuple,
      RequestCreateAuctionEvent.OutputTuple,
      RequestCreateAuctionEvent.OutputObject
    >;
  };
}
