// SPDX-License-Identifier: MIT

/**
 * @title IETSToken
 * @author Ethereum Tag Service <team@ets.xyz>
 *
 *  ███████╗████████╗███████╗
 *  ██╔════╝╚══██╔══╝██╔════╝
 *  █████╗     ██║   ███████╗
 *  ██╔══╝     ██║   ╚════██║
 *  ███████╗   ██║   ███████║`
 *  ╚══════╝   ╚═╝   ╚══════╝
 *
 * @notice This is the interface for the ETSToken.sol core contract that governs the creation & management
 * of Ethereum Tag Service tags with Zora ERC-20 coin integration.
 *
 * TAGs are represented by deterministic Zora ERC-20 coin addresses that store tag metadata including
 * three-tier identifier system, origin attribution data with "Relayer" and "Creator" addresses.
 *
 * TAGs use a three-tier identifier system: originalInput ("#BiTCOin"), displayVersion ("#Bitcoin"), 
 * and machineName ("bitcoin"). Only one TAG exists per normalized machine name regardless of case.
 *
 * TAG coin addresses are deterministically computed using Zora's coinAddress() function, enabling
 * predictable addressing and seamless integration with Zora's trading infrastructure.
 *
 * TAGs may only be generated by Relayer contracts via ETS core (ETS.sol)
 */

pragma solidity ^0.8.10;

interface IETSToken {
    /**
     * @notice Data structure for TAG Token with three-tier identifier system.
     *
     * @param originalInput Exact user input string (e.g., "#BiTCOin").
     * @param displayVersion Canonical display format (e.g., "#Bitcoin").
     * @param machineName Normalized identifier for uniqueness (e.g., "bitcoin").
     * @param coinAddress Deterministic Zora ERC-20 coin address.
     * @param creator Address interacting with relayer to initiate TAG creation.
     * @param relayer Address of relayer that facilitated TAG creation.
     * @param timestamp Block timestamp when TAG was created.
     */
    struct Tag {
        string originalInput;
        string displayVersion;
        string machineName;
        address coinAddress;
        address creator;
        address relayer;
        uint256 timestamp;
    }

    // Events

    /**
     * @dev emitted when the maximum character length of TAG display string is set.
     *
     * @param maxStringLength maximum character length of string.
     */
    event TagMaxStringLengthSet(uint256 maxStringLength);

    /**
     * @dev emitted when the minimum character length of TAG display string is set.
     *
     * @param minStringLength minimum character length of string.
     */
    event TagMinStringLengthSet(uint256 minStringLength);


    /**
     * @dev emitted when the ETS core contract is set.
     *
     * @param ets ets core contract address.
     */
    event ETSCoreSet(address ets);

    /**
     * @dev emitted when the ETS Access Controls is set.
     *
     * @param etsAccessControls contract address access controls is set to.
     */
    event AccessControlsSet(address etsAccessControls);



    /**
     * @dev emitted when a new TAG is created with Zora coin integration.
     *
     * @param coinAddress Deterministic Zora ERC-20 coin address (primary identifier).
     * @param originalInput Exact user input string (e.g., "#BiTCOin").
     * @param displayVersion Canonical display format (e.g., "#Bitcoin").
     * @param machineName Normalized identifier (e.g., "bitcoin").
     * @param creator Address credited with creating the TAG.
     * @param relayer Address of relayer that facilitated creation.
     * @param timestamp Block timestamp when TAG was created.
     */
    event TagCreated(
        address indexed coinAddress,
        string originalInput,
        string displayVersion,
        string machineName,
        address indexed creator,
        address indexed relayer,
        uint256 timestamp
    );

    // ============ OWNER INTERFACE ============

    /**
     * @notice Admin function to set maximum character length of TAG display string.
     *
     * @param _tagMaxStringLength maximum character length of string.
     */
    function setTagMaxStringLength(uint256 _tagMaxStringLength) external;

    /**
     * @notice Admin function to set minimum character length of TAG display string.
     *
     * @param _tagMinStringLength minimum character length of string.
     */
    function setTagMinStringLength(uint256 _tagMinStringLength) external;



    // ============ PUBLIC INTERFACE ============

    /**
     * @notice Get TAG coin address from tag string.
     *
     * Combo function that accepts a tag string and returns its coin address if it exists,
     * or creates a new TAG and returns corresponding coin address.
     *
     * Only ETS Core can call this function.
     *
     * @param _tag Tag string.
     * @param _relayer Address of Relayer contract calling ETS Core.
     * @param _creator Address credited with creating TAG.
     * @return coinAddress Zora ERC-20 coin address.
     */
    function getOrCreateTagId(
        string calldata _tag,
        address payable _relayer,
        address payable _creator
    ) external payable returns (address coinAddress);

    /**
     * @notice Create TAG with Zora coin integration from tag string.
     *
     * Reverts if tag exists or is invalid.
     *
     * Only ETS Core can call this function.
     *
     * @param _tag Tag string.
     * @param _relayer Address of relayer that facilitated TAG creation.
     * @param _creator Address credited with creating TAG.
     * @return coinAddress Deterministic Zora ERC-20 coin address.
     */
    function createTag(
        string calldata _tag,
        address payable _relayer,
        address payable _creator
    ) external payable returns (address coinAddress);


    // ============ PUBLIC VIEW FUNCTIONS ============

    /**
     * @notice Function to deterministically compute & return a TAG coin address.
     *
     * Every TAG and its associated data struct is mapped by its deterministic Zora coin address.
     * This address is computed using Zora's coinAddress() function with normalized machine name.
     *
     * Note: Function does not verify if TAG record exists.
     *
     * @param _tag Tag string.
     * @return coinAddress Deterministic Zora ERC-20 coin address.
     */
    function computeCoinAddress(string memory _tag) external pure returns (address);

    /**
     * @notice Check that a TAG exists for a given tag string.
     *
     * @param _tag Tag string.
     * @return true if TAG exists; false if not.
     */
    function tagExistsByString(string calldata _tag) external view returns (bool);

    /**
     * @notice Check that TAG exists for a given coin address.
     *
     * @param _coinAddress Zora ERC-20 coin address.
     * @return true if TAG exists; false if not.
     */
    function tagExistsByAddress(address _coinAddress) external view returns (bool);


    /**
     * @notice Retrieve a TAG record for a given tag string.
     *
     * Note: returns a struct with empty members when no TAG exists.
     *
     * @param _tag Tag string.
     * @return TAG record as Tag struct.
     */
    function getTagByString(string calldata _tag) external view returns (Tag memory);

    /**
     * @notice Retrieve a TAG record for a given coin address.
     *
     * Note: returns a struct with empty members when no TAG exists.
     *
     * @param _coinAddress Zora ERC-20 coin address.
     * @return TAG record as Tag struct.
     */
    function getTagByAddress(address _coinAddress) external view returns (Tag memory);

    /**
     * @notice Retrieve wallet address for ETS Platform.
     *
     * @return wallet address for ETS Platform.
     */
    function getPlatformAddress() external view returns (address payable);

}
