/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { ETSRelayerBeacon } from "./ETSRelayerBeacon";
export type { ETSRelayerV1 } from "./ETSRelayerV1";
