/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as uupsTestingSol from "./UUPSTesting.sol";
export { ETSRelayerV2test__factory } from "./ETSRelayerV2test__factory";
export { MaliciousBidder__factory } from "./MaliciousBidder__factory";
export { WMATIC__factory } from "./WMATIC__factory";
