/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IETSEnrichTarget,
  IETSEnrichTargetInterface,
} from "../../../contracts/interfaces/IETSEnrichTarget";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "targetId",
        type: "uint256",
      },
    ],
    name: "RequestEnrichTarget",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_targetId",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "_ipfsHash",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "_httpStatus",
        type: "uint256",
      },
    ],
    name: "fulfillEnrichTarget",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_targetId",
        type: "uint256",
      },
    ],
    name: "requestEnrichTarget",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IETSEnrichTarget__factory {
  static readonly abi = _abi;
  static createInterface(): IETSEnrichTargetInterface {
    return new utils.Interface(_abi) as IETSEnrichTargetInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IETSEnrichTarget {
    return new Contract(address, _abi, signerOrProvider) as IETSEnrichTarget;
  }
}
