import { BigInt } from "@graphprotocol/graph-ts";
import { MintTag, ETSTag } from "../generated/ETS/ETSTag";
import { Tag } from "../generated/schema";
import {
  toLowerCase,
  safeLoadOwner,
  safeLoadPlatform,
  safeLoadPublisher,
  ONE,
  safeLoadCreator,
} from "../utils/helpers";

/*
 * Track the minting of a tag
 *
 * event.params.tokenId NFT ID of the tag
 * event.params.tag Tag text
 * event.params.owner Owner of the new tag
 * event.params.publisher Publisher which facilitated the tag
 * event.params.publisherFee Fee earned by the publisher
 * event.params.platformFee Fee earned by ETS
 *
 * Notes
 *  In addition to the data generated by a tag, further data points are generated:
 *   - Count of how many tags owned by an Ethereum address
 *   - Fees earned by the platform and publishers across all minting events
 */
export function handleMintTag(event: MintTag): void {
  let tagEntity = new Tag(event.params.tokenId.toString());
  let tagContract = ETSTag.bind(event.address);
  let tag = tagContract.tokenIdToTag(event.params.tokenId);

  tagEntity.name = tag.value2;
  tagEntity.displayTag = event.params.displayVersion;

  let displayTag: string = event.params.displayVersion;
  let lowerTag: string = toLowerCase(displayTag);

  tagEntity.tag = lowerTag;
  tagEntity.tagWithoutHash = lowerTag.substring(1, lowerTag.length);

  tagEntity.owner = tagContract.platform();
  tagEntity.creator = tag.value1;
  tagEntity.publisher = event.params.publisher;
  tagEntity.timestamp = event.block.timestamp;
  tagEntity.tagCount = BigInt.fromI32(0);
  tagEntity.ownerRevenue = BigInt.fromI32(0);
  tagEntity.publisherRevenue = BigInt.fromI32(0);
  tagEntity.protocolRevenue = BigInt.fromI32(0);
  tagEntity.creatorRevenue = BigInt.fromI32(0);
  tagEntity.save();

  let owner = safeLoadOwner(event.params.creator.toHexString());

  if (owner) {
    owner.mintCount = owner.mintCount.plus(ONE);
    owner.save();
  }

  // publisher
  let publisher = safeLoadPublisher(event.params.publisher.toHexString());

  if (publisher) {
    publisher.mintCount = publisher.mintCount.plus(ONE);
    publisher.save();
  }

  // platform
  let platform = safeLoadPlatform("platform");

  if (platform) {
    platform.save();
  }

  // creator
  let creator = safeLoadCreator(tag.value1.toHexString());

  if (creator) {
    creator.mintCount = creator.mintCount.plus(ONE);
    creator.save();
  }
}